version: '2'

services:
  web:
    build: .
    environment:
      - SIAB_USER=student
      - SIAB_PASSWORD=cabbageface
      - SIAB_HOME=/home/student
      - SIAB_SSL=false
    ports: 
      - 4200:4200
